In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Chargement
df = pd.read_csv("C:/Users/PC/-airbnb-paris-eda-/data/raw/listings.csv.gz", compression="gzip")

# Vue d'ensemble
print(df.shape)          # (lignes, colonnes)
print(df.dtypes)         # types de chaque colonne
df.head()                 # 5 premières lignes

(81853, 79)
id                                                int64
listing_url                                      object
scrape_id                                         int64
last_scraped                                     object
source                                           object
                                                 ...
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
Length: 79, dtype: object

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2719440,https://www.airbnb.com/rooms/2719440,20250912034503,2025-09-12,previous scrape,Nice flat close to Montparnasse,This beautiful apartment is very well located ...,"The neighborhood is very nice, feel free to sh...",https://a0.muscache.com/pictures/295786e7-116c...,13915159,...,4.94,4.86,4.73,7510702406383,f,1,1,0,0,0.57
1,2721397,https://www.airbnb.com/rooms/2721397,20250912034503,2025-09-12,previous scrape,"Marais - Charming loft, river view","In the heart of historical Paris le Marais, gr...",Le Marais is the heart of Paris. Few years ago...,https://a0.muscache.com/pictures/de55313f-9b4b...,13925876,...,4.95,4.91,4.85,7510400455677,f,1,1,0,0,0.66
2,2726092,https://www.airbnb.com/rooms/2726092,20250912034503,2025-09-12,previous scrape,Superbe 2 pièces idéalement placé,A stone's throw from Parc Monceau and the Arc ...,Quiet and residential area... Close to the Bat...,https://a0.muscache.com/pictures/6d6c4bc6-9473...,13612373,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
3,2726327,https://www.airbnb.com/rooms/2726327,20250912034503,2025-09-12,previous scrape,"Cozy place, Sacré Coeur Montmartre in the SoPi",Cozy apartment close to everything.<br />Perfe...,One of the most trendy corners of the capital ...,https://a0.muscache.com/pictures/6b569382-aed7...,7483725,...,4.97,4.92,4.67,7510901014972,f,1,1,0,0,0.72
4,2727929,https://www.airbnb.com/rooms/2727929,20250912034503,2025-09-12,previous scrape,Appartement d'architecte - Montmartre,"Our apartment, refurbished by an architect in ...",The apartment is in the heart of Paris's 18th ...,https://a0.muscache.com/pictures/miso/Hosting-...,13960346,...,5.00,4.57,5.00,7511808333770,f,1,1,0,0,0.25

In [4]:
# Valeurs manquantes — essentiel à analyser

missing = df.isnull().sum().sort_values(ascending=False)
missing_pct = (missing / len(df) * 100).round(1)
pd.DataFrame({'manquants': missing, '%': missing_pct}).head(20)

                              manquants      %
bathrooms                         81853  100.0
calendar_updated                  81853  100.0
estimated_revenue_l365d           81853  100.0
beds                              81853  100.0
neighbourhood_group_cleansed      81853  100.0
price                             81853  100.0
host_neighbourhood                53855   65.8
host_about                        45350   55.4
neighbourhood                     42253   51.6
neighborhood_overview             42253   51.6
host_response_rate                32205   39.3
host_response_time                32205   39.3
host_acceptance_rate              26130   31.9
review_scores_value               17978   22.0
review_scores_checkin             17978   22.0
review_scores_location            17977   22.0
review_scores_accuracy            17971   22.0
review_scores_communication       17969   22.0
review_scores_cleanliness         17968   22.0
last_review                       17960   21.9

In [5]:
# Colonnes utiles à garder pour l'analyse

colonnes = ['id', 'name', 'neighbourhood_cleansed', 'room_type','price', 'number_of_reviews', 'review_scores_rating','accommodates', 'bedrooms', 'availability_365']
df_light = df[colonnes].copy()
df_light.describe()

,id,price,number_of_reviews,review_scores_rating,accommodates,bedrooms,availability_365
count,8.185300e+04,0.0,81853.000000,63893.000000,81853.000000,66426.000000,81853.000000
mean,6.474769e+17,NaN,27.227970,4.734384,3.221788,1.469816,127.253100
std,5.533184e+17,NaN,61.907599,0.386406,1.684614,0.867096,135.215101
min,3.109000e+03,NaN,0.000000,0.000000,1.000000,0.000000,0.000000
25%,3.124670e+07,NaN,1.000000,4.640000,2.000000,1.000000,0.000000
50%,8.417510e+17,NaN,7.000000,4.840000,3.000000,1.000000,74.000000
75%,1.130166e+18,NaN,28.000000,5.000000,4.000000,2.000000,264.000000
max,1.482029e+18,NaN,4040.000000,5.000000,16.000000,41.000000,365.000000